### PR TITLE
fix: get the raw title of the pull request (#418)

### LINKED ISSUE #418: Build script failes to create a new issue in Zally project
Error:
```
+curl -X POST -H 'Content-Type: application/json' -H 'Authorization: token [secure]' --data '{"title":""feat: improved definition of same api for x-api-id (#378)"", "body": "Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/410 introduces changes which are relevant to the Zally project.", "labels": ["guidelines-update"]}' https://api.github.com/repos/zalando/zally/issues
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   380  100   123  100   257    309    647 --:--:-- --:--:-- --:--:--   647
{
  "message": "Problems parsing JSON",
  "documentation_url": "https://developer.github.com/v3/issues/#create-an-issue"
}
```

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Fixes #418

### CODE REVIEW

**Comment by whiskeysierra** [comment]
:+1:

File: travis_deploy.sh [hunk 1]
```diff
@@ -41,7 +41,7 @@ create_zally_issue () {
     done
 
     if [ "$content_changed" = true ]; then
-        local title=$(curl -s ${GH_REPO_URL}/pulls/${pr_number} | jq '.title')
+        local title=$(curl -s ${GH_REPO_URL}/pulls/${pr_number} | jq -r '.title')
```
Comment (ePaul) [inline travis_deploy.sh]: This could break if the title has quotes in it, or other stuff which needs to be escaped in JSON strings. Maybe instead we should use the title with the quotes when building the request below?

Comment (maxim-tschumak) [reply travis_deploy.sh]: You are right, this may fail. I replace the quotes in the raw title - this should work for the most cases

File: travis_deploy.sh [hunk 2]
```diff
@@ -41,7 +41,7 @@ create_zally_issue () {
     done
 
     if [ "$content_changed" = true ]; then
-        local title=$(curl -s ${GH_REPO_URL}/pulls/${pr_number} | jq '.title')
+        local title=$(curl -s ${GH_REPO_URL}/pulls/${pr_number} | jq -r '.title' | sed s/\"/\'/g)
```
Comment (tkrop) [inline travis_deploy.sh]: Why not escaping them as usual with `sed "s/\"/\\\"/g"`?

**Comment by tkrop** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:
